/**
 * Unwaffle
 * The [Unwaffle](https://unwaffle.com) API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Unwaffle) {
      root.Unwaffle = {};
    }
    root.Unwaffle.Label = factory(root.Unwaffle.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Label model module.
   * @module model/Label
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Label</code>.
   * @alias module:model/Label
   * @class
   * @param shortCode {String} 
   */
  var exports = function(shortCode) {
    var _this = this;

    _this['ShortCode'] = shortCode;



  };

  /**
   * Constructs a <code>Label</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Label} obj Optional instance to populate.
   * @return {module:model/Label} The populated <code>Label</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ShortCode')) {
        obj['ShortCode'] = ApiClient.convertToType(data['ShortCode'], 'String');
      }
      if (data.hasOwnProperty('LabelName')) {
        obj['LabelName'] = ApiClient.convertToType(data['LabelName'], 'String');
      }
      if (data.hasOwnProperty('LabelDescription')) {
        obj['LabelDescription'] = ApiClient.convertToType(data['LabelDescription'], 'String');
      }
      if (data.hasOwnProperty('LabelType')) {
        obj['LabelType'] = ApiClient.convertToType(data['LabelType'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} ShortCode
   */
  exports.prototype['ShortCode'] = undefined;
  /**
   * @member {String} LabelName
   */
  exports.prototype['LabelName'] = undefined;
  /**
   * @member {String} LabelDescription
   */
  exports.prototype['LabelDescription'] = undefined;
  /**
   * @member {String} LabelType
   */
  exports.prototype['LabelType'] = undefined;



  return exports;
}));


