/**
 * Unwaffle
 * The [Unwaffle](https://unwaffle.com) API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Action', 'model/Label', 'model/Participant'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Action'), require('./Label'), require('./Participant'));
  } else {
    // Browser globals (root is window)
    if (!root.Unwaffle) {
      root.Unwaffle = {};
    }
    root.Unwaffle.TransportObject = factory(root.Unwaffle.ApiClient, root.Unwaffle.Action, root.Unwaffle.Label, root.Unwaffle.Participant);
  }
}(this, function(ApiClient, Action, Label, Participant) {
  'use strict';




  /**
   * The TransportObject model module.
   * @module model/TransportObject
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TransportObject</code>.
   * @alias module:model/TransportObject
   * @class
   * @param participant {module:model/Participant} 
   * @param label {module:model/Label} 
   */
  var exports = function(participant, label) {
    var _this = this;

    _this['Participant'] = participant;
    _this['Label'] = label;

  };

  /**
   * Constructs a <code>TransportObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransportObject} obj Optional instance to populate.
   * @return {module:model/TransportObject} The populated <code>TransportObject</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Participant')) {
        obj['Participant'] = Participant.constructFromObject(data['Participant']);
      }
      if (data.hasOwnProperty('Label')) {
        obj['Label'] = Label.constructFromObject(data['Label']);
      }
      if (data.hasOwnProperty('Action')) {
        obj['Action'] = Action.constructFromObject(data['Action']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Participant} Participant
   */
  exports.prototype['Participant'] = undefined;
  /**
   * @member {module:model/Label} Label
   */
  exports.prototype['Label'] = undefined;
  /**
   * @member {module:model/Action} Action
   */
  exports.prototype['Action'] = undefined;



  return exports;
}));


