/**
 * Unwaffle
 * The [Unwaffle](https://unwaffle.com) API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TransportObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/TransportObject'));
  } else {
    // Browser globals (root is window)
    if (!root.Unwaffle) {
      root.Unwaffle = {};
    }
    root.Unwaffle.ActionApi = factory(root.Unwaffle.ApiClient, root.Unwaffle.TransportObject);
  }
}(this, function(ApiClient, TransportObject) {
  'use strict';

  /**
   * Action service.
   * @module api/ActionApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ActionApi. 
   * @alias module:api/ActionApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addAction operation.
     * @callback module:api/ActionApi~addActionCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add an action
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/TransportObject} opts.body A TransportObject describing the action. The API will also happily consume a CSV or TSV with one record per line and no header row.
     * @param {module:api/ActionApi~addActionCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addAction = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json', 'text/csv'];
      var accepts = ['text/plain'];
      var returnType = null;

      return this.apiClient.callApi(
        '/action', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
