/**
 * Unwaffle
 * The [Unwaffle](https://unwaffle.com) API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Unwaffle);
  }
}(this, function(expect, Unwaffle) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Unwaffle.Participant();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Participant', function() {
    it('should create an instance of Participant', function() {
      // uncomment below and update the code to test Participant
      //var instane = new Unwaffle.Participant();
      //expect(instance).to.be.a(Unwaffle.Participant);
    });

    it('should have the property participantIdentifier (base name: "ParticipantIdentifier")', function() {
      // uncomment below and update the code to test the property participantIdentifier
      //var instane = new Unwaffle.Participant();
      //expect(instance).to.be();
    });

    it('should have the property participantUsername (base name: "ParticipantUsername")', function() {
      // uncomment below and update the code to test the property participantUsername
      //var instane = new Unwaffle.Participant();
      //expect(instance).to.be();
    });

    it('should have the property participantFullName (base name: "ParticipantFullName")', function() {
      // uncomment below and update the code to test the property participantFullName
      //var instane = new Unwaffle.Participant();
      //expect(instance).to.be();
    });

    it('should have the property participantEmail (base name: "ParticipantEmail")', function() {
      // uncomment below and update the code to test the property participantEmail
      //var instane = new Unwaffle.Participant();
      //expect(instance).to.be();
    });

    it('should have the property participantPhotoUrl (base name: "ParticipantPhotoUrl")', function() {
      // uncomment below and update the code to test the property participantPhotoUrl
      //var instane = new Unwaffle.Participant();
      //expect(instance).to.be();
    });

    it('should have the property participantStatus (base name: "ParticipantStatus")', function() {
      // uncomment below and update the code to test the property participantStatus
      //var instane = new Unwaffle.Participant();
      //expect(instance).to.be();
    });

    it('should have the property participantSignupDate (base name: "ParticipantSignupDate")', function() {
      // uncomment below and update the code to test the property participantSignupDate
      //var instane = new Unwaffle.Participant();
      //expect(instance).to.be();
    });

  });

}));
