/**
 * Unwaffle
 * The [Unwaffle](https://unwaffle.com) API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Action', 'model/Label', 'model/Participant', 'model/TransportObject', 'api/ActionApi', 'api/LabelApi', 'api/ParticipantApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Action'), require('./model/Label'), require('./model/Participant'), require('./model/TransportObject'), require('./api/ActionApi'), require('./api/LabelApi'), require('./api/ParticipantApi'));
  }
}(function(ApiClient, Action, Label, Participant, TransportObject, ActionApi, LabelApi, ParticipantApi) {
  'use strict';

  /**
   * The__Unwaffle_httpsunwaffle_com_API_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Unwaffle = require('index'); // See note below*.
   * var xxxSvc = new Unwaffle.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Unwaffle.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Unwaffle.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Unwaffle.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Action model constructor.
     * @property {module:model/Action}
     */
    Action: Action,
    /**
     * The Label model constructor.
     * @property {module:model/Label}
     */
    Label: Label,
    /**
     * The Participant model constructor.
     * @property {module:model/Participant}
     */
    Participant: Participant,
    /**
     * The TransportObject model constructor.
     * @property {module:model/TransportObject}
     */
    TransportObject: TransportObject,
    /**
     * The ActionApi service constructor.
     * @property {module:api/ActionApi}
     */
    ActionApi: ActionApi,
    /**
     * The LabelApi service constructor.
     * @property {module:api/LabelApi}
     */
    LabelApi: LabelApi,
    /**
     * The ParticipantApi service constructor.
     * @property {module:api/ParticipantApi}
     */
    ParticipantApi: ParticipantApi
  };

  return exports;
}));
